# Generated by Django 3.2.9 on 2021-11-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=600)),
                ('text', models.TextField()),
            ],
        ),
    ]
