# Generated by Django 3.2.9 on 2021-12-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailer',
            field=models.URLField(blank=True),
        ),
    ]
