# Generated by Django 3.2.9 on 2021-12-01 17:58

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kino', '0005_alter_film_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='trailer',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
